### ISSUE TITLE
Beacon update not accepting data

### ISSUE THREAD

**Issue by rv888** [Beaconstac/api#2]
Hello, I am attempting to update a beacon's notification. As far as I can tell, I am passing all required fields but I always get the following:
{"major": ["This field is required."], "UUID": ["This field is required."], "minor": ["This field is required."]}

Example data:
{"notifications": [{"is_default": true, "description": "desc update", "id": 1383893, "title": "Title Update"}], "major": 17181, "place": 8133, "name": "0117C5980F77", "campaign": {"campaign_active": true, "id": 21851, "content_type": 1, "custom_url": "https://myurl.com/url/"}, "organization": 4199, "id": 22248, "minor": 39326, "UUID": "F94DBB23-2266-7822-3782-57BEAC0952AC"}

What am I missing?

**Comment by firecast** [comment]
I tried making the same request with the data you provided. Your request is missing language_code in the `notification` object. Here is the request body I made the request in
`{
  "notifications": [
    {
      "is_default": true,
      "description": "desc update",
      "id": 1383893,
      "title": "Title Update",
      "language_code": "en"
    }
  ],
  "major": 17181,
  "place": 8133,
  "name": "0117C5980F77",
  "campaign": {
    "campaign_active": true,
    "id": 21851,
    "content_type": 1,
    "custom_url": "https://myurl.com/url/"
  },
  "organization": 4199,
  "id": 22248,
  "minor": 39326,
  "UUID": "F94DBB23-2266-7822-3782-57BEAC0952AC"
}`
 and I was able to update your beacon.

Can you share a screenshot of the PUT request you are making using Postman?

**Comment by rv888** [comment]
I am using Python requests.put to do this. Attaching an example script to run. The response is still the same for me after adding language_code. I am able to do python requests.get and filter just fine. But doing a put is failing somehow.

```
import requests

BEACONSTAC_TOKEN = ""

beacon_id = "22248"
beaconstac_url = "https://beaconstac.mobstac.com/api/2.0/beacons/"

BEACON_PARAMS = { "notifications": [ { "is_default": True, "description": "desc update 2", "id": 1383893, "title": "Title Update2 ", "language_code": "en" } ], "major": 17181, "place": 8133, "name": "0117C5980F77", "campaign": { "campaign_active": True, "id": 21851, "content_type": 1, "custom_url": "https://myurl.com/url/" }, "organization": 4199, "id": 22248, "minor": 39326, "UUID": "F94DBB23-2266-7822-3782-57BEAC0952AC" }

r = requests.put(url=beaconstac_url+beacon_id,headers={"Authorization": "Token " + BEACONSTAC_TOKEN}, data=BEACON_PARAMS)

print r.text 
```

**Comment by rv888** [comment]
Ok, so I figured out what I need to do. The URL needed to have a trailing slash. I also needed to include content type for JSON and convert my object to JSON.

Doesn't work:
https://beaconstac.mobstac.com/api/2.0/beacons/22248 

Works:
https://beaconstac.mobstac.com/api/2.0/beacons/22248/

The code below works
```
r = requests.put(url=beaconstac_url+beacon_id+"/",
                         headers={"Content-Type": "application/json","Authorization": "Token " + BEACONSTAC_TOKEN}, data=json.dumps(BEACON_PARAMS))
```
We can mark this as closed.
