### ISSUE TITLE
Disabling a beacon?

### ISSUE THREAD

**Issue by rv888** [Beaconstac/api#3]
What API field disables a beacon similar to the DISABLE button inside the control panel?

**Comment by firecast** [comment]
Because the enabling/disabling of the beacon directly affects your invoice and your subscription, we currently haven't made this API public.

**Comment by rv888** [comment]
Ok. We are looking for a way to stop a beacon from making a notification occur sometimes. As an example, if the location a beacon is at is not currently offering anything, we don't want a notification to be sent to anyone walking by. But say a week from now, this location does start to offer something. We would need to start/stop the notifications. Is this possible somehow?

**Comment by ravipratapm** [comment]
Hi Ryan,

You can do that by setting the content_type field to 0 - "No campaign" on the Campaign object:

https://github.com/Beaconstac/api#campaign-object

**Comment by rv888** [comment]
Understood. Thanks!
